version: '3'

services:
  nats:
    image: nats
    command:
      - '--jetstream'
      - '--debug'
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  integration-tester:
    build: .
    depends_on:
      - nats
    volumes:
      - ".:/app"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        composer install
        vendor/bin/phpunit --testdox
        
        
