name: Test

on: push

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        php: ['7.0', '7.1', '7.2', '7.3', '7.4']
#    services:
#      mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: wordpress_test
#        ports:
#          - 3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
      - uses: "ramsey/composer-install@v2"
      - name: PHPUnit
        run: |
          vendor/bin/phpunit